### PR TITLE
Improve coverage rate and some bugs fix for commands.py

### PR DESCRIPTION
**Pull request by iblis17**
This branch is base on [test_dispatch](https://github.com/iblis17/couchapp/tree/test_dispatch) (issue #161).

I write test cases for the function in `commands.py` **except**:
1. Some parts of `pushapps`
2. whole `pushdocs`
3. whole `vendor`

Those function contain too many logical block. It's too complicated to write unit testing.
I will open new branch and issue to deal with them.

This PR also includes some bugs fix:
- iblis17/couchapp#2
- iblis17/couchapp#4
- iblis17/couchapp#6

BTW, if we need to examine the coverage report,
as README.rst says, run:
```
nosetests --tc-file=tests/config.ini --with-coverage --cover-package=couchapp --cover-html
```
Then, there is a dir `cover` generated by `converage.py`.
Please take a look at `couchapp_commands.html`.

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@iblis17 could you rebase this off `master` now that #161 is merged?

Also, couple project health bits:
 - be sure to keep topic branches small(er)--in this case there's a handful of bugs fixed; ideally just fix one per PR (when possible)
 - be sure to log issues on the main project vs. a personal fork--this makes it easier for project tracking should your personal fork go away later. It also allows others watching the project to get notified of new issues as their made.

On the coverage note, we actually have coveralls.io setup:
https://coveralls.io/github/couchapp/couchapp

So once these are merged the badge in the readme should be much better than 30%--which is much better than the 16% it was at before you started all this great work. :smile: :+1: 

Thanks, @iblis17 !

**Comment by iblis17** [comment]
@BigBlueHat Rebased. :)

I'm sorry that this PR is too big.

I want to show you my pain point during development:

1. When I start to working on a branch for `comands.py`, I expect there is few or no bug. At first, I create a `test_commands.py`, finished test case for some of functions, and everything is fine.
2. I invoke some bug durring writting test. I think I should fix it first and write some test cases as well.
    Now, two options flashed into my mind:
    1. Maybe i should create a branch based on current master which do not contain `test_commands.py`. Fix this bugs and send PR first.
    2. Maybe i should just fix it at current working branch, log it via github issue tracker.
3. I choose the second option. Because of following concerns:
    1. If i branch from master and fix it, I will need to create a "new" `test_commands.py`, but there is a `test_commands.py` at my branch already. I think i will need share common code (like some `import`) in `test_commands.py`.
    2. if i branch from master, fix it, and send as a PR. This PR will conflict with my previous working branch. Because of both branch create their own `test_commands.py`.

So i need some suggestion or article, tell me how to solve it under this scenario.

I open issue on my fork because I notice that there is fewer and fewer people watch this repo. Maybe i am too noisy....

One more question: 
  Please tell me more about this work model: using `patch`?
  When to use patch; when to use pull request?
commit

**Comment by BigBlueHat** [comment]
@iblis17 I think you're doing great. :smile: We'll work out a good process together. The rule of thumb is trying to keep things to "topic branches." Since we're doing a code review style process at the moment, keeping the PR's short enough for other devs to understand in a reasonable amount of time is helpful. The longer (and more mixed) the content of the PR is, the longer it'll take for the other dev to get their head around the PR and to get it merged--hence the lag time here...sorry. :frowning: 

Pull Requests essentially replace the use of `patch`. Patch is useful in a workflow where you're using email to share "pull request" (conceptually). Pull Requests (the feature) actually just streamline the code sharing process and make using `patch` unnecessary...at least while the shared server is up. :wink:

Thanks for all you're doing, @iblis17. I hope to get this merged shortly.

**Comment by BigBlueHat** [comment]
Merged (after rebase) here 1f602c35b8b8c658e354b608b7b848b7522f9de0

Much thanks @iblis17 !

**Pull request closed without merging**
