### PR TITLE
add microanalytics and scrapboard to couchapp list.

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@fiatjaf sorry for the lag! Apparently my notifications for this repo aren't set high enough...

It looks like the link to the demo for Scrapboard goes to the GitHub page. Could you fix that and resubmit?

I'll be more than happy to click merge. :)

**Comment by BigBlueHat** [comment]
@fiatjaf you still here? :smile: I'd like to merge this if you can fix that link.

Cheers!

**Comment by fiatjaf** [comment]
Ok, I'll do that. The problem is that I deleted this directory from my computer and from GitHub and so lost my PR branch. GitHub keeps it, but I'm being too lazy to learn how to get it back. But I will do it.

**Comment by BigBlueHat** [comment]
@fiatjaf actually, don't worry about it. :smiley: I'm about to merge an commit that switches the docs to RST (the Python-preferred doc format which works with Sphinx).

So...they'd need redoing anyhow. I'll try and get them added to the RST once that's merged...or you can if you're bored. :wink:

**Comment by BigBlueHat** [comment]
This was taken care of as part of #163. Thanks!

**Pull request closed without merging**
