### PR TITLE
[#186][appveyor] build standalone binary!

### PR DESCRIPTION
**Pull request by iblis17**
More details are in third commit.

Please take a look at artifacts [here](https://ci.appveyor.com/project/iblis17/couchapp/build/job/guiy5q2m6w9q9p9k/artifacts).

I do not know much about windows scripting. :fearful:
Maybe the `appveyor.yaml` is too ugly to understand.
So let me know if you need my explanation.

But I have no idea why [the binary build with python-x64](https://ci.appveyor.com/project/iblis17/couchapp/build/job/1sej5w8777uav7j8/artifacts) not work....
Actually, the win32 one works fine with my 64-bit windows vm.
Maybe we should warn user not to download the win64 one.

### CODE REVIEW

**Comment by BigBlueHat** [comment]
Does this have the latest stuff from @broerse's work? Could we incorporate this into a release process--even if we just avoid "shipping" the win64 build artifacts?

**Comment by iblis17** [comment]
@BigBlueHat The stuff from @benoitc works fine :)

BTW, it seems that the link of artifact is unavailable. The correct one is here:
https://ci.appveyor.com/project/iblis17/couchapp/build/1.0.74/job/guiy5q2m6w9q9p9k/artifacts

**Comment by BigBlueHat** [comment]
Worked great from my quick test! Thanks, @iblis17 We'll use this artifact output for the next release.

**Comment by BigBlueHat** [comment]
Too many buttons... :confused:

**Comment by iblis17** [comment]
Please also setup the appveyor for this repo and add badge to README. :tada:

**Pull request merged**
