### PR TITLE
CouchApp docs reorganization draft

### PR DESCRIPTION
**Pull request by iblis17**
The commit logs are too long; don't read.
[Here](http://iblis17.github.io/couchapp/) is the bleeding edge build of docs from my fork.

I preserve most of contents from the old archive.
So there is still some pages required to update, or some article came from a blog post need to be rewritten as a formal documentation.
Here is a list of questionable pages:
  - [x] ~~[installing-on-mac-os-x](http://iblis17.github.io/couchapp/couchapp/install.html#installing-on-mac-os-x) : Need help testing on newer OSX and newer version of `couchapp.py`~~ header note added
  - [x] ~~[installing-on-ubuntu](http://iblis17.github.io/couchapp/couchapp/install.html#installing-on-ubuntu) : PPA... do we still support this?~~ header note added
  - [x] ~~[usage](http://iblis17.github.io/couchapp/couchapp/usage.html) : more commands~~ header note added
  - [x] ~~[garden](http://iblis17.github.io/couchapp/user/garden.html) : I really want to rebuild this garden, any idea about hosting?~~ header note added
  - [x] ~~[roadmap](http://iblis17.github.io/couchapp/dev/roadmap.html)~~ Header note added
  - [x] ~~[What is CouchApp?](http://iblis17.github.io/couchapp/dev/roadmap.html) : It seems that this page came from a blog post. It need to be rewritten.~~
  - [X] ~~[Videos](http://iblis17.github.io/couchapp/user/videos.html): hmm .. everything was gone.~~ Let's rebuild the *relaxedtv*!

And some works need to take effors on:
  - [ ] Merge docs from github wiki
  - [x] ~~Merge #154~~ (9bb2b97)
  - [ ] sphinx side bar

If you think something missing, please comment it or contribution!

@BigBlueHat 
BTW, the `docs` dir can be imported via Read The Doc. We can benifit from the auto building.
So how about hosting our doc on RTD? If not ,please remember to build sphinx and push to github page manully. :)

### CODE REVIEW

**Comment by wu-lee** [comment]
Had some spare time, so I just had a quick look. Reads OK, can't yet comment on correctness, except for a few broken links, which you may know about.  See the last point for a link to the old couchapp database on iriscouch.

I noticed:

* landing page (index.html)
  * Links to Evently and its docs are 404s, evently repo link is https://github.com/jchris/evently, (which ironically and now incorrectly links back to couchapp.org for "extensive documentation")
  * Some evently info found here: https://jameswestby.net/weblog/tech/20-couchapp-walkthrough-part-3-evently.html

* filesystem-mapping.html
  * Evently primer link is 404, don't know a working one

* dev-tools.html
  * is the list item mentioning filesystem-mapping.html meant to be a link?

* what-is-couchapp.html
  * link to Pathbinder, Evently are 404's.    Can't find a working pathbinder repo/manual.

* [later] Some guesswork finds the docs for evently and pathbinder at iriscouch (which is IIRC what couchone became).
  * http://couchapp.iriscouch.com/docs/_design/docs/index.html#/topic/pathbinder
  * http://couchapp.iriscouch.com/docs/_design/docs/index.html#/topic/evently
  * In fact, this turns up a whole bunch of stuff in http://couchapp.iriscouch.com/_utils/, which looks like it includes the couchdb garden

**Comment by iblis17** [comment]
Hi @wu-lee!
Thanks for the info of iriscouch's db. That's a big help.

- index.html: I cannot find any link about Evently on our [index.html](http://iblis17.github.io/couchapp/index.html) ...
- filesystem-mapping.html
    - [x] ~~Pathbinder~~ Fixed
    - [x] ~~Evently repo~~ Fixed
    - [ ] Evently Primer: There is a link around [here](https://github.com/iblis17/couchapp/blob/cce170cc879cc027ff5efac5b197462982a52f56/docs/design/filesystem-mapping.rst#evently).The raw docs of Evently Primer is here:
		http://couchapp.iriscouch.com/pages/evently-primer
	at the field `markdown`.
	I will work on extracting it later.

- [x] ~~dev-tools.html~~ Fixed

**Comment by wu-lee** [comment]
Re: index.html - maybe my mistake.

**Comment by iblis17** [comment]
@wu-lee
`Evently primer` imported. 
Please [check it out](http://iblis17.github.io/couchapp/js/evently-primer.html), thx!

**Comment by iblis17** [comment]
BTW, is there any logo of _couchapp.org_?
If exists, we can put it at the side bar of docs.

**Comment by wu-lee** [comment]
Read it through, links (there aren't many) all seem fine, reads fine too.

And I learnt what Evently is (except for the CouchDB specifics, which it 
appears not to cover.)

Thanks!

**Comment by BigBlueHat** [comment]
Great work @iblis17 and @wu-lee!

ReadTheDocs is setup: https://readthedocs.org/projects/couchapp/ :clap: 

The relaxed.tv code: https://github.com/maxogden/relaxed.tv
...but sadly no videos any longer. :frowning: 

Evently stuff should actually be put in the [Evently repo](https://github.com/couchapp/evently). It's pretty dead as a project, so I'd actually prefer we keep it out of the couchapp.py docs and out of any boilerplate apps we generate. :+1: to sending a PR there, though. I think I can get it added. :smiley:

Let's keep the questionable pages with the header notes, and just keep working on making the docs more awesome. :smile: Sound good?

Once the Evently stuff is out, I'm :+1: on merging this and RTD should auto-update once it's on master. Then we can start reworking the docs to be more focused on the future as well as hunt down other interested folks to help add and/or link to content.

Oh! One last thing, can you change the copyright to "Various CouchApp Contributors" and (if possible) link to the [contributors list](https://github.com/couchapp/couchapp/graphs/contributors) on GitHub? That'd be best as most of this content is written by lots of different people. We can discuss licensing, etc on the mailing list or somewhere later.

Much thanks for all this work, @iblis17. @wu-lee thanks for all your help also! You both are super fabulous. :grinning:

**Comment by iblis17** [comment]
Hi @BigBlueHat !
Copyright changed.

It seems that there is no `Evently` in our boilerplate app already.
So i will purge the docs of `Evently`, then send a docs PR to Evently repo.

**Comment by BigBlueHat** [comment]
:+1: I'll merge it once that's done. Thanks!

**Comment by iblis17** [comment]
We can get some video back from [archive.org](https://web.archive.org/web/20130719210522/http://www.relaxed.tv/) !! :tada:

**Comment by BigBlueHat** [comment]
@iblis17 you're a genius!!!

Here's some more links to help extract data:
* https://web.archive.org/web/20150828142851/http://www.relaxed.tv/api/_all_docs
* https://web.archive.org/web/20150828142943/http://www.relaxed.tv/api/videos?include_docs=true

Pretty sure that last link should let us put all the video docs (30 afaict) into a new database and put it back online! Woot woot! :tada:

**Comment by iblis17** [comment]
@BigBlueHat 

For those questionable pages, the header notes added. You can merge this PR first.

And let's rebuild the *relaxedtv* :tada:
We can replicate *relaxedtw* from [here](http://max.iriscouch.com/apps/_design/relaxedtv/)
Any suggestion for hosting? It seems that iriscouch isn't alive...

**Pull request merged**
