### PR TITLE
Deprecate supporting of py26

### PR DESCRIPTION
**Pull request by iblis17**
I will remove the legacy code during writing testing and code refinement. :)

### CODE REVIEW

**Comment by benoitc** [comment]
removing 2.6 will remove a lot of pro users....

**Comment by iblis17** [comment]
:-o ... hmm user of RHEL 6...?
Or currently we can just show some warning to user ?

**Comment by benoitc** [comment]
no currently 40% of the python users are still under py 2.6. Not really an
issue if ir's shipped as a bin though...

**Comment by iblis17** [comment]
40%?!
That's really beyond my imagination.
ok... so seems support for py26 is unavoidable...

**Comment by benoitc** [comment]
Sorry it's between 10-20% according some sources. There was a presentation with latest figure at pycon US with the latest figures but can't remember its title. Still for example we can't remove the python 2.6 support easily in Gunicorn. So I would suggest doing 2 steps:

1. make a release now that include everything
2. Go for a new major version that won't include any new features and only be compatible with Python 2.7 or better 3.

Anyway if couchapp is shipped with a distributions or as a standalone binary, this is not a problem at all... You can use the version you want :)

**Comment by iblis17** [comment]
About shipping with a distribution, you mean we can provide something like PPA or AUR? I agree this way is better for user friendly.

About standalone binary, I will start to survey PyInstaller. :smile: 

So, maybe we finally will suggest/provide user who do not understand python installing via binary;
for developer/contributor, let them install from pypi/source.

**Comment by BigBlueHat** [comment]
Yeah. Agree with the above. @benoitc's bullet points about cutting a release soon (once all the other fabulous PR's are in!) and then working toward a new major point release that drops 2.6 support makes good sense.

I'm going to close this one to keep the space clean, but feel free to bring it back soon. :smile:

**Pull request closed without merging**
